### ISSUE TITLE
ERROR in /opt/resource/out : line 234 with exit code 1

### ISSUE THREAD

**Issue by skreddy6673** [cathive/concourse-sonarqube-resource#59]
Concourse pipeline failing with following errors, Any help would be helpful.

```
Digest: sha256:3a273ba13f295e2d6400d89151c15390b5b129ebdb67bc65589dc57a850d5dde
Status: Downloaded newer image for cathive/concourse-sonarqube-resource@sha256:3a273ba13f295e2d6400d89151c15390b5b129ebdb67bc65589dc57a850d5dde

Successfully pulled cathive/concourse-sonarqube-resource@sha256:3a273ba13f295e2d6400d89151c15390b5b129ebdb67bc65589dc57a850d5dde.

Preparing SonarQube scanner...
ERROR in /opt/resource/out : line 234 with exit code 1
```

```
Digest: sha256:c8aff28e93d7cfddc4b975f467a52b7d7cd21d433451d52c1ea88a23d382fc9d
Status: Downloaded newer image for cathive/concourse-sonarqube-resource@sha256:c8aff28e93d7cfddc4b975f467a52b7d7cd21d433451d52c1ea88a23d382fc9d

Successfully pulled cathive/concourse-sonarqube-resource@sha256:c8aff28e93d7cfddc4b975f467a52b7d7cd21d433451d52c1ea88a23d382fc9d.

Preparing SonarQube scanner...
ERROR in /opt/resource/out : line 255 with exit code 1
```
```
Status: Downloaded newer image for cathive/concourse-sonarqube-resource@sha256:aad9ff30d95c158a86b523aac9d308d97d52956617a257be2d1019287be56a85

Successfully pulled cathive/concourse-sonarqube-resource@sha256:aad9ff30d95c158a86b523aac9d308d97d52956617a257be2d1019287be56a85.

Preparing SonarQube scanner...
ERROR in /opt/resource/out : line 234 with exit code 1
```

**Comment by skreddy6673** [comment]
This pipeline once worked with image 0.10.0.

**Comment by headcr4sh** [comment]
Thanks for the bug report.

Please set the configuration parameter `__debug` to `true` and run the resource again.

The verbose output might provide some insights into this bug.

**Comment by skreddy6673** [comment]
Adding `_debug: true` under resource didn't display any additional output.

**Comment by headcr4sh** [comment]
It's `__debug: true` (notice that there are two underscores in front of the key!!)

**Comment by skreddy6673** [comment]
Sorry got pulled into other things,
@headcr4sh Actually debug option woked, my bad i didn't notice two underscores.  
```
- name: validate-pr
  plan:
  - get: pull-request
    trigger: true
    version: every
  - get: pipeline-source
  - params:
      path: pull-request
      status: pending
    put: pull-request
  - get: scm-source
  - config:
      caches:
      - path: maven
      container_limits: {}
      image_resource:
        source:
          repository: maven
          tag: 3.6-jdk-8
        type: docker-image
      inputs:
      - name: pull-request
      - name: pipeline-source
      outputs:
      - name: sonarqube-analysis-input
      platform: linux
      run:
        args:
        - -xce
        - |
          M2_HOME="${HOME}/.m2"
          M2_CACHE="$(pwd)/maven"
          ln -s $M2_CACHE $M2_HOME
          cd pull-request
          ls
          mvn --batch-mode -s maven_settings.xml clean package
          cd ..
          cp -r pull-request/* sonarqube-analysis-input
          cd sonarqube-analysis-input
#          ls
        path: /bin/sh
    on_failure:
      params:
        comment: Maven build FAILED for this pull request
        path: pull-request
        status: failure
      put: pull-request
    task: unit-test
  - params:
      additional_properties:
        sonar.scm.disabled: true
      project_key: submissions-api
      project_path: sonarqube-analysis-input
      maven_settings_file: sonarqube-analysis-input/maven_settings.xml
      sources:
      - .
    put: code-analysis
  public: true
```

This is my job and after adding the maven_settings_file location path it's able to pick it up but somehow failing with following error
```
[ERROR] Error executing Maven.
java.io.FileNotFoundException: The specified user settings file does not exist: /tmp/build/put/sonarqube-analysis-input/sonarqube-analysis-input/maven_settings.xml
```
I don't know why it's looking for `sonarqube-analysis-input/sonarqube-analysis-input/` at the same location twice.
