### ISSUE TITLE
Params that contain whitespaces fail the build

### ISSUE THREAD

**Issue by headcr4sh** [cathive/concourse-sonarqube-resource#6]
Whitespaces in params lead to errors during invocation of the sonar-scanner executable (Maven and CLI)

Example (excerpt of Job that uses "my-sonar-analysis" as SonarQube resource):
```yaml
  - put: my-sonar-analysis
    params:
      project_path: src
      project_key: "com.example.my_project"
      project_name: MyProject
      project_description: My fancy project ## << this won't work. :-(
```
